### ISSUE TITLE
Idea: Add report to get all Pages by label

### ISSUE THREAD

**Issue by wernerkrauss** [JZubero/silverstripe-sitetree-labels#2]
A report to get e.g. all Pages that are "to review" would be awesome.

**Comment by JZubero** [comment]
You are thinking sth. like this? https://prnt.sc/h0418g
Which purpose do you have in mind?

**Comment by wernerkrauss** [comment]
On a deeply nested SiteTree with tons of pages it's hard to get all pages that are set "to review" (or any other label) otherwise.
