### ISSUE TITLE
Nested LI's not showing correctly in CMS

### ISSUE THREAD

**Issue by blueskies79** [JZubero/silverstripe-sitetree-labels#5]
Hi! I am a huge fan of your module, cleans up our sitetrees very nicely, thank you for sharing!

I discovered a bug with nested sitetree items. The case I had was a root-level item, with subitems, and subsubitems. Whenever the root-level item was expanded (by clicking the little arrow and /admin/pages/getsubtree?ID=...&ajax=1 was called), the interface moved all subitem and subsubitems up one level in the interface. They weren't actually reparented (the database still showed them to be subitems of the correct parent), but the tree moved them up. I traced the origin of the bug back to a closing </li> that apparently is not needed. So my solution was to change the LeftAndMain_TreeNode.ss to the following (basically I just removed the </li> at the end ;-) ): 

```
<li id="record-$ID" data-id="$ID" data-pagetype="$ClassName" class="$Classes"><ins class="jstree-icon">&nbsp;</ins>
    <a href="$Link" title="$Title.ATT"><ins class="jstree-icon">&nbsp;</ins>
        <span class="text">$TreeTitle</span>
        <% if $SiteTreeLabels %>
            <% loop $SiteTreeLabels %>
                <span class="sitetree-label" style="background-color: $Color">TT $Title</span>
            <% end_loop %>
        <% end_if %>
    </a>
```
This is in line with /framework/admin/template/Includes/LeftAndMain_TreeNode.ss (which also has no ending </li>). Could you incorporate this fix with the next version?

**Comment by JZubero** [comment]
@blueskies79 I'm glad you could use the module! Thanks for reporting the issue and providing the fix - great bug tracing ;) Patch is coming up!
